# Generated by Django 5.1.4 on 2024-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_practical_interest', models.IntegerField(default=0)),
                ('min_analytical_interest', models.IntegerField(default=0)),
                ('min_artistic_interest', models.IntegerField(default=0)),
                ('min_social_interest', models.IntegerField(default=0)),
                ('min_enterprising_interest', models.IntegerField(default=0)),
                ('min_conventional_interest', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('interest_type', models.CharField(choices=[('practical', 'Practical Interest'), ('analytical', 'Analytical Interest'), ('artistic', 'Artistic Interest'), ('social', 'Social Interest'), ('enterprising', 'Enterprising Interest'), ('conventional', 'Conventional Interest')], max_length=50)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('practical_interest', models.IntegerField(default=0)),
                ('analytical_interest', models.IntegerField(default=0)),
                ('artistic_interest', models.IntegerField(default=0)),
                ('social_interest', models.IntegerField(default=0)),
                ('enterprising_interest', models.IntegerField(default=0)),
                ('conventional_interest', models.IntegerField(default=0)),
            ],
        ),
    ]
