# Generated by Django 5.1.4 on 2024-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='career_paths',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='example_subjects',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='skills_required',
            field=models.TextField(default=''),
        ),
    ]
