# Generated by Django 5.1.4 on 2024-12-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_fieldofstudy_career_paths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='interest_type',
            field=models.CharField(choices=[('practical', 'Practical Interest'), ('analytical', 'Analytical Interest'), ('artistic', 'Artistic Interest'), ('social', 'Social Interest'), ('enterprising', 'Enterprising Interest'), ('conventional', 'Conventional Interest'), ('scientific', 'Scientific Interest'), ('technical', 'Technical Interest')], max_length=50),
        ),
    ]
