# Generated by Django 5.1.4 on 2024-12-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_testquestion_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging')], default='Moderate', max_length=15),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='min_scientific_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='min_technical_interest',
            field=models.IntegerField(default=0),
        ),
    ]
